apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-operator-cluster
  namespace: default
spec:
  security:
    config:
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9200
    serviceName: opensearch-operator-cluster
    version: 2.3.0
  nodePools:
    - component: masters
      replicas: 1
      resources:
         requests:
            memory: "100Mi"
            cpu: "1000m"
      roles:
        - "master"
      persistence:
         emptyDir: {}
    - component: client
      replicas: 1
      resources:
         requests:
            memory: "100Mi"
            cpu: "1000m"
      roles: []
      persistence:
         emptyDir: {}
    - component: "data-content"
      replicas: 1
      resources:
         requests:
            memory: "100Mi"
            cpu: "1000m"
      roles:
        - "data"
      persistence:
        emptyDir: {}
      additionalConfig:
        node.attr.temp: content
    - component: "data-hot"
      replicas: 3
      resources:
         requests:
            memory: "100Mi"
            cpu: "1000m"
      roles:
        - "data"
      persistence:
        emptyDir: {}
      additionalConfig:
        node.attr.temp: hot
    - component: "data-warm"
      replicas: 2
      resources:
         requests:
            memory: "100Mi"
            cpu: "1000m"
      roles:
        - "data"
      persistence:
        emptyDir: {}
      additionalConfig:
        node.attr.temp: warm
    - component: "data-cold"
      replicas: 1
      resources:
         requests:
            memory: "100Mi"
            cpu: "1000m"
      roles:
        - "data"
      persistence:
        emptyDir: {}
      additionalConfig:
        node.attr.temp: cold