version: '3'

services:
  opensearch-master:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-master
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=cluster_manager
      - node.name=opensearch-master # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-master:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    ports:
      # - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-client:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-client
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=[]
      - node.name=opensearch-client # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-client:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    ports:
      - 9200:9200 # REST API
      # - 9600:9600 # Performance Analyzer
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-data-content:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-data-content
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=data
      - node.attr.temp=content
      - node.name=opensearch-data-content # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      # - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data-content:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-data-hot-1:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-data-hot-1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=data
      - node.attr.temp=hot
      - node.name=opensearch-data-hot-1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      # - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data-hot-1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-data-hot-2:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-data-hot-2
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=data
      - node.attr.temp=hot
      - node.name=opensearch-data-hot-2 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      # - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data-hot-2:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-data-hot-3:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-data-hot-3
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=data
      - node.attr.temp=hot
      - node.name=opensearch-data-hot-3 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      # - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data-hot-3:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-data-warm-1:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-data-warm-1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=data
      - node.attr.temp=warm
      - node.name=opensearch-data-warm-1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      # - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data-warm-1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-data-warm-2:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-data-warm-2
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=data
      - node.attr.temp=warm
      - node.name=opensearch-data-warm-2 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      # - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data-warm-2:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-data-cold-1:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-data-cold-1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=data
      - node.attr.temp=cold
      - node.name=opensearch-data-cold-1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      # - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data-cold-1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-data-cold-2:
    image: opensearchproject/opensearch:latest # Specifying the latest available image - modify if you want a specific version
    container_name: opensearch-data-cold-2
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.roles=data
      - node.attr.temp=cold
      - node.name=opensearch-data-cold-2 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-master # Nodes to look for when discovering the cluster
      # - cluster.initial_cluster_manager_nodes=opensearch-master # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - opendistro.rollup.search.enabled=false
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data-cold-2:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
      - ../opensearch.yml:/usr/share/opensearch/config/opensearch.yml
      - opensearch-snapshots:/mount/snapshots
    networks:
      - opensearch-net # All of the containers will join the same Docker bridge network
  opensearch-dashboards:
    build:
      context: ../dashboard
      dockerfile: Dockerfile
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch-client:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - opensearch-net

volumes:
  opensearch-master:
  opensearch-data-content:
  opensearch-data-hot-1:
  opensearch-data-hot-2:
  opensearch-data-hot-3:
  opensearch-data-warm-1:
  opensearch-data-warm-2:
  opensearch-data-cold-1:
  opensearch-data-cold-2:
  opensearch-data-2:
  opensearch-client:
  opensearch-snapshots:

networks:
  opensearch-net: